devtools::install_github("thomasp85/patchwork")
devtools::install_github("ropensci/magick")
devtools::install_github("GuangchuangYu/ggimage")
install.packages("ggrepel", repos="https://cran.rstudio.com")
#devtools::install_github("GuangchuangYu/ggimage")
