devtools::install_github("thomasp85/patchwork")
devtools::install_github("ropensci/magick")
install.packages("palmerpenguins", repos="https://cran.rstudio.com")
install.packages("ggrepel", repos="https://cran.rstudio.com")
setRepositories(ind=1:2)
devtools::install_github("GuangchuangYu/ggimage")
